apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nodejs-chat-deployment 
spec: 
  replicas: 3 
  selector: 
   matchLabels: 
    app: nodejs-chat 
  template: 
   metadata: 
    labels: 
     app: nodejs-chat 
   spec: 
    containers:
     - name: nodejs-chat 
       image: "gcr.io/qwiklabs-gcp-04-1d18bfe5c01d/nodejs-chat-app:{{DOCKER_IMAGE_TAG}}" 
       ports: 
         - containerPort: 3000
